- name: kubeadm init
  shell:
    kubeadm init  \
      --kubernetes-version=v1.18.6 \
      --pod-network-cidr=172.16.0.0/16 \
      --service-cidr=10.96.0.0/12 \
      --apiserver-advertise-address=0.0.0.0 \
      --apiserver-bind-port=6443 \
      --control-plane-endpoint="{{ urls.kubeadm.url }}":6443 \
      --image-repository="{{ urls.registry.url }}/kubernetes" \
      --upload-certs
  register: kubeadm_info

- name: copy kubeconfig (1/)
  file:
    path: $HOME/.kube
    state: directory

- name: copy kubeconfig (2/)
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes

- name: get discovery-token-ca-cert-hash
  shell: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null|openssl dgst -sha256 -hex|sed 's/^.* //'"
  register: ca_cert_hash

- name: get init token
  shell: "kubeadm token list|grep init|awk {'print $1'}"
  register: kubeadm_token

- name: create kubeadm_info tmp file
  copy:
    content: "{{ kubeadm_info.stdout }}"
    dest: /tmp/kubeadm_info

- name: get certificate-key
  shell: grep ' --certificate-key' /tmp/kubeadm_info|awk {'print $3'}
  register: certificate_key

- name: add fact
  set_fact:
    certificate_key: "{{ certificate_key }}"
    kubeadm_token: "{{ kubeadm_token }}"
    ca_cert_hash: "{{ ca_cert_hash }}"

- name: apply calico (1/)
  template:
    src: calico.yml.j2
    dest: /tmp/calico.yml

- name: apply calico (2/)
  shell: kubectl apply -f /tmp/calico.yml