- name: apply metrics (1/)
  template:
    src: metrics.yml.j2
    dest: /tmp/metrics.yml
  when: ansible_facts['default_ipv4']['address'] == special_roles.k8s_master_1

- name: apply metrics (2/)
  shell: kubectl apply -f /tmp/metrics.yml
  when: ansible_facts['default_ipv4']['address'] == special_roles.k8s_master_1

- name: apply treafik (1/)
  template:
    src: "{{ item.src }}"
    dest: "/tmp/{{ item.dest }}"
  loop:
    - { src: 'treafik.yml.j2', dest: 'treafik.yml' }
    - { src: 'treafik_rbac.yml.j2', dest: 'treafik_rbac.yml' }
    - { src: 'treafik_service.yml.j2', dest: 'treafik_service.yml' }
  when: ansible_facts['default_ipv4']['address'] == special_roles.k8s_master_1

- name: apply treafik (2/)
  shell: kubectl apply -f /tmp/{{ item }}
  loop:
    - treafik_rbac.yml
    - treafik_service.yml
    - treafik.yml
  when: ansible_facts['default_ipv4']['address'] == special_roles.k8s_master_1

