- name: set hostname
  hostname:
    name: "{{ hostname[ ansible_facts[ 'default_ipv4' ] [ 'address' ] ] }}"

- name: add hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: stop firewalld - 1
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: stop selinux - 1
  shell:
    setenforce 0

- name: stop selinux - 2
  replace:
    path: /etc/selinux/config
    regexp: "SELINUX=.*"
    replace: "SELINUX=disabled"

- name: close swapoff - 1
  shell:
    swapoff -a

- name: close swapoff - 2
  shell:
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: clear iptables
  shell: iptables -F && iptables -X && sudo iptables -F -t nat && sudo iptables -X -t nat

- name: add defalut iptables
  shell:
    iptables -P FORWARD ACCEPT

- name: yum repo server
  include_tasks: yum_repo_server.yml
  when: ansible_facts['default_ipv4']['address'] == urls.repo.ip
  tags: create_repo_server

- name: try remove yum.repos.d/bak
  file:
    path: /etc/yum.repos.d/bak
    state: absent
  ignore_errors: true

- name: clear yum.repo.d
  shell: 'cd /etc/yum.repos.d/ && mkdir bak && mv ./*.repo bak/'
  ignore_errors: true

- name: send repo file
  template:
    src: local.repo.j2
    dest: "/etc/yum.repos.d/local.repo"

- name: Include ntp server task
  include_tasks: ntp_server.yml
  when: ansible_facts['default_ipv4']['address'] == urls.ntp.ip
  tags: ntp

- name: Include ntp client task
  include_tasks: ntp_client.yml
  when: ansible_facts['default_ipv4']['address'] != urls.ntp.ip
  tags: ntp




