- name: set hostname
  hostname:
    name: "{{ hostname[ ansible_facts[ 'default_ipv4' ] [ 'address' ] ] }}"

- name: add hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: stop firewalld - 1
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: stop selinux - 1
  shell:
    setenforce 0

- name: stop selinux - 2
  replace:
    path: /etc/selinux/config
    regexp: "SELINUX=.*"
    replace: "SELINUX=disabled"

- name: close swapoff - 1
  shell:
    swapoff -a

- name: close swapoff - 2
  replace:
    path: /etc/fstab
    regexp: " swap "
    replace: " s/^\(.*\)$/#\1"

- name: yum repo server
   include_tasks: yum_repo_server.yml

# ntp





